### ISSUE TITLE
access to ExaLearn confluence

### ISSUE THREAD

**Issue by shantenujha** [BNL-C3D/ExaLearn#3]
Ray and Gyorgy to ensure they get access to confluence site:

https://confluence.exascaleproject.org/display/ADCD08/

**Comment by YHRen** [comment]
sent email to shinjae, waiting for feedback.

**Comment by YHRen** [comment]
frank is working on it.

**Comment by shantenujha** [comment]
SJ to ping Frank!

**Comment by shantenujha** [comment]
SJ to ping Frank again.

**Comment by shantenujha** [comment]
SJ wrote to admin directly, cc-ing Frank and others.
