### ISSUE TITLE
communicate with peter on cosmology app 

### ISSUE THREAD

**Issue by YHRen** [BNL-C3D/ExaLearn#4]
There are several things we need to discuss with peter to have a better understanding of the goal and move forward. 

* communicate with peter on cosmology mini app. 
* the goal for the computation campaign. (proposing a general GAN for a range of parameters.) 
* random sampling as a starting point, as well as to establish a performance baseline.
* the requirements.

**Comment by YHRen** [comment]
sent emails to peter, waiting for feedback.

**Comment by shantenujha** [comment]
@shantenujha to link UC template in an email to Peter Nugent

**Comment by YHRen** [comment]
got reply from peter. pointed to [CosmoFlow](https://github.com/NERSC/CosmoFlow) code.

**Comment by YHRen** [comment]
read the paper and the code of cosmoflow. it is not what we are looking for. 
following up with peter.

**Comment by YHRen** [comment]
straightened the misunderstanding with peter. 
peter pointed to the full-fledged n-body simulation they use to generate cosmo 3d figures.
[pycola](https://github.com/NERSC/cosmoflow-sims/tree/master/pycola)
