### ISSUE TITLE
grant Ai access to stampede2

### ISSUE THREAD

**Issue by YHRen** [BNL-C3D/ExaLearn#8]

**Comment by shantenujha** [comment]
@aik7 Please send me your XSEDE portal uname (http://portal.xsede.org)

**Comment by aik7** [comment]
My XSEDE portal name is "aik".

**Comment by shantenujha** [comment]
This was submitted at 7:30 pm on 3/13.

**Comment by aik7** [comment]
My TACC Account has been created on 3/13.

**Comment by shantenujha** [comment]
Ai, to try a test job and then close.

**Comment by aik7** [comment]
I was able to run a test job, so now I close this issue.
